[package]
name = "uebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
ebpf-command = { path = "../ebpf-command" }
net-aya = { path = "../net-aya" }
aya = { workspace = true }
env_logger = { version = "0.11.5", default-features = false }
rand = "0.9"
